"""Scientific package-management namespace."""

from fermilink.packages.package_core import (
    PACKAGE_DEPENDENCIES_DIRNAME,
    PACKAGE_DEPENDENCY_IDS_KEY,
    PACKAGE_OVERLAY_ENTRIES_KEY,
    REGISTRY_FILENAME,
    TEMPLATE_RESERVED_ENTRY_NAMES,
    WORKSPACE_MANIFEST_FILENAME,
    atomic_write_json,
    build_default_registry,
    extract_manifest_dependency_ids,
    extract_manifest_entry_names,
    is_exportable_entry_name,
    link_or_copy_entry,
    load_registry_file,
    normalize_package_id,
    normalize_registry_payload,
    overlay_package_into_repo_core,
    remove_existing_entry,
    remove_managed_dependency_links,
    remove_managed_entries,
    save_registry_file,
)

__all__ = [
    "PACKAGE_DEPENDENCIES_DIRNAME",
    "PACKAGE_DEPENDENCY_IDS_KEY",
    "PACKAGE_OVERLAY_ENTRIES_KEY",
    "REGISTRY_FILENAME",
    "TEMPLATE_RESERVED_ENTRY_NAMES",
    "WORKSPACE_MANIFEST_FILENAME",
    "atomic_write_json",
    "build_default_registry",
    "extract_manifest_dependency_ids",
    "extract_manifest_entry_names",
    "is_exportable_entry_name",
    "link_or_copy_entry",
    "load_registry_file",
    "normalize_package_id",
    "normalize_registry_payload",
    "overlay_package_into_repo_core",
    "remove_existing_entry",
    "remove_managed_dependency_links",
    "remove_managed_entries",
    "save_registry_file",
]
